---
exclude_paths:
  - collectors/python.d.plugin/python_modules/pyyaml2/**
  - collectors/python.d.plugin/python_modules/pyyaml3/**
  - collectors/python.d.plugin/python_modules/urllib3/**
  - collectors/python.d.plugin/python_modules/lm_sensors.py
  - web/gui/css/**
  - web/gui/lib/**
  - '*.min.js'
  - collectors/node.d.plugin/node_modules/**
  - tests/**
