# docs: https://lgtm.com/help/lgtm/lgtm.yml-configuration-file

extraction:

  # docs: https://lgtm.com/help/lgtm/javascript-extraction
  javascript:
    filters:
      - exclude: "node.d/node_modules/lib/**"
      - exclude: "node.d/node_modules/lib/ber/**"
      - exclude: "node.d/node_modules/asn1-ber.js"
      - exclude: "node.d/node_modules/extend.js"
      - exclude: "node.d/node_modules/net-snmp.js"
      - exclude: "node.d/node_modules/pixl-xml.js"
      - exclude: "web/lib/**"
      - exclude: "tests/**"

  # docs: https://lgtm.com/help/lgtm/python-extraction
  python:
    prepare:
      packages: urllib3 pyyaml3
    python_setup:
      version: 3
      setup.py: false
    filters:
      - exclude: "python.d/python_modules/third_party/**"
      - exclude: "python.d/python_modules/urllib3/**"
      - exclude: "python.d/python_modules/pyyaml2/**"
      - exclude: "python.d/python_modules/pyyaml3/**"
      - exclude: "tests/**"

