# docs: https://lgtm.com/help/lgtm/lgtm.yml-configuration-file

extraction:

  # docs: https://lgtm.com/help/lgtm/javascript-extraction
  javascript:
    index:
      filters:
        - exclude: "node.d/node_modules/lib/*"
        - exclude: "node.d/node_modules/lib/ber/*"
        - exclude: "node.d/node_modules/asn1-ber.js"
        - exclude: "node.d/node_modules/extend.js"
        - exclude: "node.d/node_modules/net-snmp.js"
        - exclude: "node.d/node_modules/pixl-xml.js"
        - exclude: "web/lib/*"
        - exclude: "tests/*"
        - exclude: "tests/web/*"
        - exclude: "tests/web/lib/*"
        - exclude: "tests/web/fixtures/*"
        - exclude: "tests/profile/*"
        - exclude: "tests/node.d/*"

  # docs: https://lgtm.com/help/lgtm/python-extraction
  python:
    #prepare:
    #  packages: urllib3 pyyaml3
    python_setup:
      version: 3
    index:
      filters:
        - exclude: "python.d/python_modules/third_party/*"
        - exclude: "python.d/python_modules/urllib3/*"
        - exclude: "python.d/python_modules/urllib3/util/*"
        - exclude: "python.d/python_modules/urllib3/packages/*"
        - exclude: "python.d/python_modules/urllib3/packages/backports/*"
        - exclude: "python.d/python_modules/urllib3/packages/ssl_match_hostname/*"
        - exclude: "python.d/python_modules/urllib3/contrib/*"
        - exclude: "python.d/python_modules/urllib3/contrib/_securetransport/*"
        - exclude: "python.d/python_modules/pyyaml2/*"
        - exclude: "python.d/python_modules/pyyaml3/*"
        - exclude: "tests/*"
        - exclude: "tests/web/*"
        - exclude: "tests/web/lib/*"
        - exclude: "tests/web/fixtures/*"
        - exclude: "tests/profile/*"
        - exclude: "tests/node.d/*"
