dist: trusty
sudo: true
language: c
services:
- docker

stages:
- test
- build
- name: packaging
  if: branch = master AND type != pull_request AND type != cron
- name: nightlies
  if: branch = master AND type = cron
- name: Integrity testing
  if: branch = master AND type = cron

jobs:
  include:
  - stage: test
    name: C
    install: sudo apt-get install -y libcap2-bin zlib1g-dev uuid-dev fakeroot libipmimonitoring-dev libmnl-dev libnetfilter-acct-dev
    script: fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it --enable-plugin-nfacct --enable-plugin-freeipmi --disable-lto && $HOME/netdata/usr/sbin/netdata -W unittest
    env: CFLAGS='-O1 -DNETDATA_INTERNAL_CHECKS=1 -DNETDATA_VERIFY_LOCKS=1'
  - name: dashboard.js
    script: cp web/gui/dashboard.js /tmp/dashboard.js && ./build/build.sh && diff /tmp/dashboard.js web/gui/dashboard.js
  - name: lint .sh.in files
    script: shellcheck --format=gcc $(find . -name '*.sh.in' -not -iwholename '*.git*')
  - name: check checksums for kickstart files
    script: ./tests/installer/checksums.sh
    env: LOCAL_ONLY="true"
  - name: coverity
    install: sudo apt-get install -y zlib1g-dev uuid-dev libipmimonitoring-dev libmnl-dev libnetfilter-acct-dev
    script: ./coverity-install.sh && ./coverity-scan.sh || echo "Coverity failed :("
    if: type = cron

  - stage: build
# TODO: enable when travis OSX become stable. Probably after 12.01.2019
#   name: OSX
#   install: brew install fakeroot ossp-uuid
#   script: fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it
#   os: osx
# - name: ubuntu 14.04 (not containerized)
    name: ubuntu 14.04 (not containerized)
    install: sudo apt-get install -y libcap2-bin zlib1g-dev uuid-dev fakeroot
    script: fakeroot ./netdata-installer.sh --dont-wait --dont-start-it --install $HOME
  - name: build container (alpine installation)
    script: ./packaging/docker/build.sh
    env: DEVEL="true"
  - name: ubuntu 18.04 + lifecycle
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:ubuntu1804" bats --tap tests/lifecycle.bats
  - name: CentOS 7
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:centos7" ./netdata-installer.sh --dont-wait --dont-start-it --install /tmp
  - name: CentOS 6
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:centos6" ./netdata-installer.sh --dont-wait --dont-start-it --install /tmp

  - stage: packaging
    name: Create release (only on special commit msg)
    install:
    - sudo apt-get install -y gnupg libcap2-bin zlib1g-dev uuid-dev fakeroot python-pip
    - sudo apt install -y --only-upgrade docker-ce
    - docker info
    before_script: sudo pip install git-semver
    script: ".travis/releaser.sh && .travis/labeler.sh" # labeler should be replaced with GitHub Actions when they hit GA
    git:
      depth: false

  - stage: nightlies
    name: Nightly build
    before_install: openssl aes-256-cbc -K $encrypted_8daf19481253_key -iv $encrypted_8daf19481253_iv -in .travis/gcs-credentials.json.enc -out .travis/gcs-credentials.json -d
    install:
    - sudo apt-get install -y gnupg libcap2-bin zlib1g-dev uuid-dev fakeroot
    - sudo apt install -y --only-upgrade docker-ce
    - docker info
    script: ".travis/nightlies.sh"
    git:
      depth: false
    deploy:
      provider: gcs
      edge:
        branch: gcs-ng
      project_id: netdata-storage
      credentials: .travis/gcs-credentials.json
      bucket: "netdata-nightlies"
      skip_cleanup: true
      local_dir: "artifacts"
    after_deploy: rm -f .travis/gcs-credentials.json

  - stage: Integrity testing
    name: Kickstart files integrity testing
    script: ./tests/installer/checksums.sh

notifications:
  email:
    recipients:
    - paul@netdata.cloud
    on_success: always
    on_failure: always
  webhooks: https://app.fossa.io/hooks/travisci
  slack:
    secure: CFKaJTbLKijcfATB+nmX4KwBKp8j0wQfq+z9XbZmfoLfscw/+YuIn3DImkyN9SYsTN9ZgPflzvO10pYtHQCSj/CXZCFBw1pR3DV3vhDTf3Q9KA3qfbwjeN0brC0dIkWBBhkr7MZbNaIRAqCijyMpOWLVbx9/RTn4G7Nh3satmKaJoknvFd2rfjtf18Gc+V56PyrfSapgJ+e4bRcbf3aSMPFwG0nAJrHPjKWUr+gacu24/i2wHGhOK33+lSHSBJK3hx3uk7Q6OxoPmFCahrgAiZfxfjU3Ppa096ZdF3BODH4ujn8tHyxQbL/j4c0jBUTUp8rbESWmiIkGLuJQgcMUyDhAbMFkmjLt39RjBbR76tcOd3G9xJLYdgqCJo4BxmKBYhuFfPRgr7fEOwlMwUsCf74UtI7VjSijhpWQlqDqtYb9nKghhKkCG1NI7rxRMdo6Gjn1E4Cq4Soyy1ctO+hT6sCemt+ozVmzcYwTiDd30ZxrqLdr0qA8hkwLxQr45bpX2ppp/d04s5ZufuC/8vnjG04z4C9uBzc+tJRlv2HDUdsbEa8PxI9U75nz2Vma/ahYprBpF7QNUIbs5t9fpnWIjE19Dw2BzKc+k0vI3pOQJLCAQDLwNlqOGXYtLT0OiHMY2KcW7tIub6nURMVr45f7Mj2hwi6CMFZBsftLJNkY/bE=
