dist: trusty
sudo: true
language: c
services:
- docker

stages:
- test
- build
- name: packaging
  if: branch = master AND type != pull_request AND type != cron
- name: nightlies
  if: branch = master AND type = cron
- name: Integrity testing
  if: branch = master AND type = cron

jobs:
  include:
  - stage: test
    name: C
    install: sudo apt-get install -y libcap2-bin zlib1g-dev uuid-dev fakeroot libipmimonitoring-dev libmnl-dev libnetfilter-acct-dev
    script: fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it --enable-plugin-nfacct --enable-plugin-freeipmi --disable-lto && $HOME/netdata/usr/sbin/netdata -W unittest
    env: CFLAGS='-O1 -DNETDATA_INTERNAL_CHECKS=1 -DNETDATA_VERIFY_LOCKS=1'
  - name: dashboard.js
    script: cp web/gui/dashboard.js /tmp/dashboard.js && ./build/build.sh && diff /tmp/dashboard.js web/gui/dashboard.js
  - name: lint .sh.in files
    script: shellcheck --format=gcc $(find . -name '*.sh.in' -not -iwholename '*.git*')
  - name: check checksums for kickstart files
    script: ./tests/installer/checksums.sh
    env: LOCAL_ONLY="true"
  - name: coverity
    install: sudo apt-get install -y zlib1g-dev uuid-dev libipmimonitoring-dev libmnl-dev libnetfilter-acct-dev
    script: ./coverity-install.sh && ./coverity-scan.sh || echo "Coverity failed :("
    if: type = cron

  - stage: build
# TODO: enable when travis OSX become stable. Probably after 12.01.2019
#   name: OSX
#   install: brew install fakeroot ossp-uuid
#   script: fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it
#   os: osx
# - name: ubuntu 14.04 (not containerized)
    name: ubuntu 14.04 (not containerized)
    install: sudo apt-get install -y libcap2-bin zlib1g-dev uuid-dev fakeroot
    script: fakeroot ./netdata-installer.sh --dont-wait --dont-start-it --install $HOME
  - name: build container (alpine installation)
    script: ./packaging/docker/build.sh
    env: DEVEL="true"
  - name: ubuntu 18.04 + lifecycle
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:ubuntu1804" bats --tap tests/lifecycle.bats
  - name: CentOS 7
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:centos7" ./netdata-installer.sh --dont-wait --dont-start-it --install /tmp
  - name: CentOS 6
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:centos6" ./netdata-installer.sh --dont-wait --dont-start-it --install /tmp

  - stage: packaging
    name: Create release (only on special commit msg)
    install:
    - sudo apt-get install -y gnupg libcap2-bin zlib1g-dev uuid-dev fakeroot python-pip
    - sudo apt install -y --only-upgrade docker-ce
    - docker info
    before_script: sudo pip install git-semver
    script: ".travis/releaser.sh && .travis/labeler.sh" # labeler should be replaced with GitHub Actions when they hit GA
    git:
      depth: false

  - stage: nightlies
    name: Nightly build
    before_install: openssl aes-256-cbc -K $encrypted_8daf19481253_key -iv $encrypted_8daf19481253_iv -in .travis/gcs-credentials.json.enc -out .travis/gcs-credentials.json -d
    install:
    - sudo apt-get install -y gnupg libcap2-bin zlib1g-dev uuid-dev fakeroot
    - sudo apt install -y --only-upgrade docker-ce
    - docker info
    script: ".travis/nightlies.sh"
    git:
      depth: false
    deploy:
      provider: gcs
      edge:
        branch: gcs-ng
      project_id: netdata-storage
      credentials: .travis/gcs-credentials.json
      bucket: "netdata-nightlies"
      skip_cleanup: true
      local_dir: "artifacts"
    after_deploy: rm -f .travis/gcs-credentials.json

  - stage: Integrity testing
    name: Kickstart files integrity testing
    script: ./tests/installer/checksums.sh

notifications:
  email:
    recipients:
    - paul@netdata.cloud
    on_success: always
    on_failure: always
  webhooks: https://app.fossa.io/hooks/travisci
  slack:
    rooms:
      - secure: CbYKB67UQRoN737iBJRiaPnSHRnTkXuQH5VUR8+w8U5zJStX1DBpcINd3yR9FJzmre7i8QEeSEhvMPvDCPli5aTO3O01eK5/gbNINWQb1bLpSsYXk+k18xxRpq5jJOu6tfkHMWURgbRVCcwzKP4yL6Nm7v128QD575nZrxD+KnSgSjv50vEmOBBzhQ1+0X8muMoF9+coSm/EuWlVtpH57A9vysXXHkTQtCxSFjAPixtDDeSZMeMy4TbrsYohDUEIjtSjOY3tUnWfJXYdOPRYWgAKrLmks8OyQS0WwCChZrpz2sJvuIx2zqHdHhT7IFsJk4sgujX1tYBLW6F+lStNzP2E56m62VGGJSU2jWKrta/sANPeshQD0tFhUFLLnzU1SXJbX65hsdUUrafcq5HNw9JMB0gaW2zSiwMn07opLU4QRot1IECzhmXASIJgZMrPPcGJAJhHJCcO8koLyeRp5SIWJVSAdIstP1qOoHGMCiqrgGXX0okxafuD7Tm04FWwF50ib+TCpe3hhtUwk1h4CVhPMYW3Eyf5RTspyYHtMpdQ4bsbRojGjB5YrOdd1h7LyKguCamLh9PS53RDycn7xnkREBkEwjno2Y52rvS8fZc65IYgWIvrVoZy8LYKXfITf8I+YYkE3mVWT0+DY8lKdjI0FVjZq2P/LiibsXze/zE=
    on_failure: always
    on_success: always
    on_start: always
