---
style: Github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/netdata/netdata
options:
  allow_uncategorized: true
  commits:
    filters:
      Type:
        - Add
        - Fix
        - Remove
        - Update
        - Refactor
        - Document
        - Deprecate
  commit_groups:
    title_maps:
      Add: New Features
      Remove: Deprecation / Removals
      Deprecate: Deprecation / Removals
      Update: Updates and Improvements
      Refactor: Updates and Improvements
      Fix: Bug Fixes
      Document: Documentation
  header:
    pattern: "^((\\w+)\\s.*)$"
    pattern_maps:
      - Subject
      - Type
  notes:
    keywords:
      - BREAKING CHANGE
