version: '3.3'
services:
  agent_master:
    image: centos_8_dev
    command: /usr/sbin/netdata -D
    ports:
    - 20000:19999
    volumes:
    - ./master_stream.conf:/etc/netdata/stream.conf:ro
  agent_slave1:
    image: debian_buster_dev
    command: /usr/sbin/netdata -D
    ports:
    - 20001:19999
    volumes:
      - ./slave_stream.conf:/etc/netdata/stream.conf:ro
  agent_slave2:
    image: ubuntu_2004_dev
    command: /usr/sbin/netdata -D
    ports:
    - 20002:19999
    volumes:
      - ./slave_stream.conf:/etc/netdata/stream.conf:ro
