version: '3.3'
services:
  agent_master:
    build:
      context: ../../..
      dockerfile: build_external/make_install_fedora_30.Dockerfile
      args:
        ACLK: "yes"
    image: fedora_30_dev
    command: >
      sh -c "echo 00000000-0000-0000-0000-000000000000 >/etc/netdata/claim.d/claimed_id &&
             echo '[agent_cloud_link]' >>/etc/netdata/netdata.conf &&
             echo '  agent cloud link hostname = vernemq' >>/etc/netdata/netdata.conf &&
             /usr/sbin/netdata -D"
    ports:
    - 20000:19999
    #volumes:
    #- ./master_stream.conf:/etc/netdata/stream.conf:ro
#  agent_slave1:
#    image: debian_buster_dev
#    command: /usr/sbin/netdata -D
#    ports:
#    - 20001:19999
#    volumes:
#      - ./slave_stream.conf:/etc/netdata/stream.conf:ro
#  agent_slave2:
#    image: ubuntu_2004_dev
#    command: /usr/sbin/netdata -D
#    ports:
#    - 20002:19999
#    volumes:
#      - ./slave_stream.conf:/etc/netdata/stream.conf:ro
  vernemq:
    image: vernemq_configured
    depends_on: 
      - configure_step

  configure_step:
    image: vernemq_configured
    build:
      dockerfile: configureVerneMQ.Dockerfile
      context: .
