---
name: Deploy preview
on:
  pull_request:
env:
  run_eslint: 0
  run_hadolint: 0
  run_shellcheck: 0
  run_yamllint: 0
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      - name: Check out netdata/learn
        uses: actions/checkout@master
        with:
          name: netdata/learn
          path: './build'
      - name: Use Node.js 12
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 12
      - run: yarn install
      - run: node ./build/ingest.js
        env:
          GITHUB_TOKEN: ${{ secrets.INGEST_TOKEN }}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1