---
name: Updater
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  source-build:
    name: Install, Build & Update
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'debian:10'
          - 'fedora:33'
    runs-on: ubuntu-latest
    steps:
      - name: Install netdata latest
        run: bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait
      - name: Git clone repository
        uses: actions/checkout@v2
      - name: Build tarball
        run: |
          .github/scripts/build-dist.sh
      - name: Run a dockerised web server to serve files used by the update script
        run: |
          docker run -dit --name my-apache-app -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4
      - name: Replace URLs in updater script to point at the local web server
        run: |
          ORIG_TARBALL="export NETDATA_TARBALL_URL=.*"
          ORIG_CHECKSUM="export NETDATA_TARBALL_CHECKSUM_URL=.*"
          NEW_TARBALL="export NETDATA_TARBALL_URL=http://localhost:8080/artifacts/netdata-latest.tar.gz"
          NEW_CHECKSUM="export NETDATA_TARBALL_CHECKSUM_URL=http://localhost:8080/artifacts/sha256sums.txt"
          sed -i "s|${ORIG_TARBALL}|${NEW_TARBALL}|g" packaging/installer/netdata-updater.sh
          sed -i "s|${ORIG_CHECKSUM}|${NEW_CHECKSUM}|g" packaging/installer/netdata-updater.sh
      - name: Run the updater
        run: |
          netdata -V
          sudo ./packaging/installer/netdata-updater.sh
          netdata -V
